apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
  labels:
    type: nfs-pv
    
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: "/nfs/k3s/pv1"
    server: 10.0.0.154
    readOnly: false
